language: c
compiler: gcc
env:
  - TEST_DIR="LZW coder"
  - TEST_DIR="LZW decoder"
script: cd "$TEST_DIR" && make && make test
language: c
script:
  - cd "$TEST_DIR"
  - clang -coverage -O0 *.c -o main
  - ./main
  - gcov *.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
